apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-apache
  name: my-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      name: akilan-apache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: akilan-apache
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
