apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: say-hello
spec:
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: say-hello
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: ubuntu
            name: say-hello
            command: ["echo","Hello Akilan"]
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
