version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
  db-server:
    image: "mysql:5.7"
    volumes:
    - /home/vagrant/mysql-data:/var/lib/mysql
    environment:
    - MYSQLOOT_PASSWORD=admin123
    - NAME=AKILAN-PHP-APP
